spring:
  application:
    name: CustomerService

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/oauth2/jwks

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:customerDetailsDB}
    username: kprahul143
    password: kprahul143
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "com.gohul"

custom:
  kafka:
    create-group: create-id
    create-topic: create-event
    verify-group: verify-id
    verify-topic: verify-event
    delete-group: delete-id
    delete-topic: delete-event

logging:
  level:
    root: INFO
    com.gohul: INFO
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

server:
  port: 8081
